build website:
  image: node
  script:
    - npm install
    - npm config set registry http://registry.npmjs.org
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./public

test artifact:
  script:
    - grep "Gatsby" ./public/intex.html
    - grep "A_B_C_D" ./public/index.html
