build website:
  image: node
  script:
    - npm install
    - npm config set registry http://registry.npmjs.org
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./public
