image: node

stages:
  - build
  - test
  - deploy
  - deployment tests

build website:
  stage: build
  script:
    - npm install
    - npm config set registry http://registry.npmjs.org
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./public

test artifact:
  image: alpine
  stage: test
  script:
    - grep -q "Gatsby" ./public/index.html

test website:
  stage: test
  script:
    - npm install
    - npm config set registry http://registry.npmjs.org
    - npm install -g gatsby-cli
    - gatsby serve &
    - sleep 10
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"

deploy to surge:
  stage: deploy
  script:
    - npm install --global surge
    - surge --project ./public --domain intersetter.surge.sh

test deployment:
  stage: deployment tests
  image: alpine
  script:
    - sleep 10
    - apk add curl
    - curl "intersetter.surge.sh" | tac | tac | grep -q "Now go build something great."
